//-----------------------------------------------------------------------------
//  This main source file is written by adding to code template generated by
//  the Microchip Code Configurator MCC.
//  File Name:
//    main.c
//
//  Description:
//    This header file provides implementations for driver APIs for all modules 
//    selected in the GUI.
//
//    Generation Information :
//        Product Revision  :  PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.78.1
//        Device            :  PIC18F26K22
//        Driver Version    :  2.00
//-----------------------------------------------------------------------------

#include "xc.h"
#include "mcc.h"
#include "cocoos.h"
#include "audioVisual.h"
#include "edgeDetect.h"
#include "textTerm.h"
#include "i2a.h"
#include "alarm.h"
#include "opParam.h"

//-----------------------------------------------------------------------------
// Debug notes: ICD reset usually occurs multiple times in succession.11Feb2020
//-----------------------------------------------------------------------------

void main(void)
{
    //-------------------------------------------------------------------------
    // Initialization generally ordering lowest level (near hardware) first   
    // progressing towards highest level (application). 
    //-------------------------------------------------------------------------
    SYSTEM_Initialize(); //----------- MCC Microchip Code Configurator
    
    //-------------------------------------------------------------------------
    // Advanced high-low interrupt is used (configured in MCC from which source
    // code is generated). High priority interrupt custom handler code is to be
    // manually in-lined to the respective ISR to minimize latency of time-
    // critical interrupt(s).
    //-------------------------------------------------------------------------
    TMR0_SetInterruptHandler(os_tick);       //------ Allocate timer to OS tick
    //TMR3_SetInterruptHandler(adcTmr3Hanlder);
    //TMR5_SetInterruptHandler(adcTmr5Hanlder);
    //ADC_SetInterruptHandler(adcDataHandler);
    //TMR3_SetInterruptHandler(cmpTmr3Handler);
    //TMR5_SetInterruptHandler(cmpTmr5Handler);
    
    //-------------------------------------------------------------------------
    // Initialize OS before creating tasks
    //-------------------------------------------------------------------------
    os_init();

    //-------------------------------------------------------------------------
    // Watchdog policy is to be revised later. Perhaps we will place clrwdt()
    // in OS scheduler loop. 
    //-------------------------------------------------------------------------
    SWDTEN=0;
    
    //-------------------------------------------------------------------------
    // Create kernel objects
    //-------------------------------------------------------------------------
    // Third argument is task priority. Important:
    //     (1) 0..255, the smaller the number the higher the priority
    //     (2) No two tasks is to be assigned the same priority 
    //     (3) Even when scheduling scheme is "round-robin" (1) and (2) still 
    //         apply.
    // Tests the above if not observed the MCU will hang.
    //-------------------------------------------------------------------------
    u32GoEvent = event_create();
    u32DoneEvent = event_create();
    
    //task_create( adc_task,            NULL, 127, NULL, 0, 0 );
    task_create( u32Toa11_task,       NULL, 126, NULL, 0, 0 );
    task_create( av_control_task,     NULL, 128, NULL, 0, 0 );
    task_create( alarm_task,          NULL, 125, NULL, 0, 0 );
    task_create( print_task,          NULL, 129, NULL, 0, 0 );
    task_create( senseTrigger_task,   NULL, 131, NULL, 0, 0 );
    task_create( textTerminal_task,   NULL, 130, NULL, 0, 0 );
    task_create( realTimeReport_task, NULL, 127, NULL, 0, 0 );
    
    //-------------------------------------------------------------------------
    // Load operating metrics from EEPROM
    //-------------------------------------------------------------------------
    opSetPre_AlarmFromEE();
    opSetMainAlarmFromEE();
    opSetAlarmSamplingFromEE();
    opSetCmpVoltThresholdFromEE();
        
    //-------------------------------------------------------------------------
    // If using interrupts in PIC18 High/Low Priority Mode, enable the Global 
    // High and Low Interrupts.
    //-------------------------------------------------------------------------
    INTERRUPT_GlobalInterruptHighEnable();
    INTERRUPT_GlobalInterruptLowEnable();
    
    //-------------------------------------------------------------------------
    // If using interrupts in PIC Mid-Range Compatibility Mode, enable the 
    // Global and Peripheral Interrupts (not our use case, commented out and 
    // kept for reference)
    //-------------------------------------------------------------------------
    //INTERRUPT_GlobalInterruptEnable();
    //INTERRUPT_PeripheralInterruptEnable();
    
    //-------------------------------------------------------------------------
    // Entering the application (configuration and initialization are done)
    //-------------------------------------------------------------------------
    os_start();

    //-------------------------------------------------------------------------
    // Program execution (control flow) is expected to never fall to this 
    // code section since the OS is an infinite loop in nature. 
    //-------------------------------------------------------------------------
    return;
}

//----------------------------------------------------------------- end of file
